version: '3.8'

services:
  # Backend service (Node.js)
  backend:
    build:
      context: ../server
    container_name: booking-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bookingapp
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  # Frontend service (React)
  frontend:
    build:
      context: ../client
    container_name: booking-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: booking-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
